# apiVersion: v1
# kind: Service
# metadata:
#   name: task-api
#   namespace: task-api
#   labels:
#     app: task-api
# spec:
#   selector:
#     app: task-api
#   ports:
#   - port: 80
#     targetPort: 8000
#     protocol: TCP
#     name: http
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: task-api
  namespace: task-api
  labels:
    app: task-api
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      # nodePort is optional
      nodePort: 30081
  selector:
    app: task-api
